spring:
  application:
    name: sfc-workflow
  datasource:
    url: jdbc:mysql://localhost:3306/ems_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    open-in-view: false

    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never
server:
  port: 8080

jwt:
  secrete: DjJNXH8jV4WC2GRnFQeY5scndMhCK9tp6YroZhQeDgd
